### ISSUE TITLE
수취금액 유효성 검사

### ISSUE THREAD

**Issue by b41-41** [wantedPreOnboarding/19_01st_calculator#8]
수취금액이 올바른 값인지 유효성 검사

**Comment by vi2920va** [comment]
아래의 조건에 해당하는 경우 하단에 에레 메시지 표시
- 송금액을 입력하지 않았을 경우
- 수취 금액이 0 보다 작은 금액이거나 10,000 USD 보다 큰 금액일 경우
- 바른 숫자가 아닌 경우
